name: build and test

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      working-directory: ./CyborgianStates.Test
      run: |
        dotnet build ../CyborgianStates/CyborgianStates.sln
        # temporary: copy settings so tests pass. this should be removed before release
        cp ../CyborgianStates/appsettings.json bin/Debug/netcoreapp3.1/appsettings.development.json
    - name: Run tests
      working-directory: ./CyborgianStates.Test
      run: |
        dotnet tool install --global coverlet.console
        ~/.dotnet/tools/coverlet bin/Debug/netcoreapp3.1/CyborgianStates.Test.dll --target "dotnet" --targetargs "test --no-build" --exclude "[*]CyborgianStates.MessageHandling.ConsoleInput" --exclude "[*]CyborgianStates.AppSettings" --exclude "[*]CyborgianStates.Models.*" --format cobertura --output "./TestResults//"